name: cp-rec
channels:
    - pytorch
    - nvidia
    - defaults
dependencies:
    - python
    - pytorch
    - pytorch-cuda=12.1
    - requests
    - requests-ratelimiter
    - numpy
    - pandas
    - pydantic
    - pre-commit
    - pip
    - pip:
          - types-requests
          - black
          - fsspec
